# Generated by Django 3.1.1 on 2020-09-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], default='Full Time', max_length=30, null=True),
        ),
    ]
