# Generated by Django 3.1.1 on 2020-09-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0008_auto_20200919_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='yoe_req',
        ),
    ]
