# Generated by Django 3.1.1 on 2020-09-19 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0009_remove_job_yoe_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='selected',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
