# Generated by Django 3.1.1 on 2020-09-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_auto_20200918_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
