# Generated by Django 3.1.1 on 2020-09-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_job_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
    ]
